name: Sync Forks

on:
  # Run the workflow every Saturday at 7:00 AM
  schedule:
    - cron: "0 7 * * 1"
  # Manually trigger the workflow
  workflow_dispatch:

jobs:
  sync_fork:
    runs-on: ubuntu-latest
    steps:
      - name: Sync forks
        env:
            GH_TOKEN: ${{ secrets.GH_PAT }}
        run: |
          # empty array to store failed forks
          FAILED_FORKS=()
          # get all forks of the owner
          FORKS=$(gh repo list ${{ github.actor }} --fork --limit 50 --json name --jq '.[].name' | tr '\n' ' ')
          if [ -z "$FORKS" ]; then
            echo "No forks found for ${{ github.actor }}"
            exit 0
          fi
          # loop through each fork to sync
          for fork in $FORKS; do
            echo "Syncing fork: $fork"
            DEFAULT_BRANCH=$(gh repo view "$fork" --json defaultBranchRef --jq '.defaultBranchRef.name')
            gh repo sync ${{ github.actor }}/$fork -b $DEFAULT_BRANCH
            sleep 10
          done

          # tell the user which forks failed to sync
          if [ ${#FAILED_FORKS[@]} -gt 0 ]; then
            echo "Failed to sync ${#FAILED_FORKS[@]}:"
            printf '%s\n' "${FAILED_FORKS[@]}"
          fi
